# Generated by Django 5.0 on 2023-12-27 15:39

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.TextField()),
                ('title', models.TextField()),
                ('helper', models.TextField()),
                ('description', models.TextField()),
                ('youtube', models.BooleanField()),
                ('aparat', models.BooleanField()),
                ('readmore', models.BooleanField()),
                ('image', models.ImageField(upload_to=posts.models.slider_image_path)),
            ],
        ),
    ]
