# Generated by Django 5.0.1 on 2024-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_followers_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='users.city'),
        ),
    ]
