# Generated by Django 5.0.1 on 2024-05-02 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_city_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_taste', models.CharField(blank=True, max_length=100, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('social_instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('favourite_foods', models.ManyToManyField(blank=True, null=True, related_name='favourite_foods', to='users.food')),
                ('hobbies', models.ManyToManyField(blank=True, null=True, related_name='hobbies', to='users.hobby')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
