# Generated by Django 5.0.1 on 2024-05-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_food_hobby_personality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='personality',
            name='favourite_foods',
            field=models.ManyToManyField(blank=True, null=True, related_name='personalities', to='users.food'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, related_name='personalities', to='users.hobby'),
        ),
        migrations.RemoveField(
            model_name='personality',
            name='job',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='music_taste',
        ),
        migrations.AddField(
            model_name='personality',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, related_name='personalities', to='users.job'),
        ),
        migrations.AddField(
            model_name='personality',
            name='music_taste',
            field=models.ManyToManyField(blank=True, null=True, related_name='personalities', to='users.musicgenre'),
        ),
    ]
