# Generated by Django 5.0.1 on 2024-05-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_job_musicgenre_alter_personality_favourite_foods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='musicgenre',
            old_name='genre',
            new_name='name',
        ),
    ]
