# Generated by Django 5.0.1 on 2024-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_job_job_name_rename_genre_musicgenre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='favourite_foods',
            field=models.ManyToManyField(related_name='personalities', to='users.food'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='hobbies',
            field=models.ManyToManyField(related_name='personalities', to='users.hobby'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='job',
            field=models.ManyToManyField(related_name='personalities', to='users.job'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='music_taste',
            field=models.ManyToManyField(related_name='personalities', to='users.musicgenre'),
        ),
    ]
