# Generated by Django 5.0.1 on 2024-06-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_personality_favourite_foods_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='name',
        ),
    ]
