# Generated by Django 5.0.1 on 2024-07-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_city_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='favourite_foods',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='job',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='music_taste',
        ),
        migrations.RemoveField(
            model_name='personality',
            name='user',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='MusicGenre',
        ),
        migrations.DeleteModel(
            name='Personality',
        ),
    ]
