# Generated by Django 5.1 on 2024-11-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_hobby_movie_music_notification_personality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personality',
            name='job',
        ),
    ]
