# Generated by Django 5.2.1 on 2025-05-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_customuser_otp_code_customuser_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personality',
            name='fav_music',
            field=models.ManyToManyField(blank=True, related_name='musics', to='users.music'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='hobbies', to='users.hobby'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='users.movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.city'),
        ),
    ]
