# Generated by Django 5.0.1 on 2024-04-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_cafe_city_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='cafes.cafe'),
        ),
    ]
