# Generated by Django 5.0.1 on 2024-05-07 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_alter_club_cafe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='his_clubs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cafes.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='intvited',
            field=models.ManyToManyField(related_name='suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='participents',
            field=models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
