# Generated by Django 5.0.1 on 2024-05-15 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0007_alter_event_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='admin',
            field=models.ManyToManyField(related_name='cafes', to=settings.AUTH_USER_MODEL),
        ),
    ]
