# Generated by Django 5.0.1 on 2024-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_alter_cafe_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='items', to='cafes.categoryfood'),
        ),
    ]
