# Generated by Django 5.0.1 on 2024-05-19 17:46

import cafes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_categoryfood_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfood',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to=cafes.models.category_image_upload),
        ),
    ]
