# Generated by Django 5.0.1 on 2024-05-24 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_categoryfood_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
        migrations.AddField(
            model_name='club',
            name='admin',
            field=models.ManyToManyField(related_name='his_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
