# Generated by Django 5.0.1 on 2024-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_remove_club_owner_club_admin_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='number',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
