# Generated by Django 5.1 on 2024-11-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0012_cafe_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfood',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='cafe',
        ),
        migrations.AddField(
            model_name='categoryfood',
            name='cafe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cafes.cafe'),
            preserve_default=False,
        ),
    ]
