# Generated by Django 5.1 on 2024-11-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_remove_categoryfood_picture_remove_menuitem_cafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfood',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='cafes.cafe'),
        ),
    ]
