# Generated by Django 5.1 on 2024-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafes", "0015_remove_menuitem_category_menuitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
