# Generated by Django 5.1.4 on 2024-12-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0016_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='invisible',
            field=models.BooleanField(default=True),
        ),
    ]
