# Generated by Django 5.1.4 on 2025-01-05 00:02

import cafes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0017_cafe_invisible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='picture',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=cafes.models.cafe_image_upload)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='cafes.cafe')),
            ],
        ),
    ]
