# Generated by Django 5.1.4 on 2025-01-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0018_remove_cafe_picture_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
