# Generated by Django 5.1.4 on 2025-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0019_picture_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
