# Generated by Django 5.1.4 on 2025-02-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
