# Generated by Django 5.1.4 on 2025-02-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0021_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
