# Generated by Django 5.1.4 on 2025-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0022_cafe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
